# linux_debugging_tree/package/Makefile

# Include the Makefiles for each individual package/module
include $(BR2_EXTERNAL_LINUX_DEBUGGING_TREE_PATH)/package/dev_log_demo/dev_log_demo.mk
include $(BR2_EXTERNAL_LINUX_DEBUGGING_TREE_PATH)/package/pr_format_demo/pr_format_demo.mk
include $(BR2_EXTERNAL_LINUX_DEBUGGING_TREE_PATH)/package/log_demo/log_demo.mk
