#!/bin/bash

# Get staged .md files
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.md$')
if [ -z "$FILES" ]; then
    exit 0
fi

# Run the validation script on them
python3 .git/hooks/validate_doc_type.py $FILES
RESULT=$?

exit $RESULT

#This should be added in .git/hooks/pre-commit,